# Required to build the app and provides a default for the docker image
# DO NOT DELETE!

[email]
enabled = false
verification = false

[incidents.auto]
enabled = true
pings_threshold = 3

[storage]
max_size = 12582912

[users]
delete_on_empty = false

[workspace]
creation = true
