name: Publish

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata for web app
              id: meta-web
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/web

            - name: Build and push Docker image for web app
              id: push-web
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/web
                  push: true
                  tags: ${{ steps.meta-web.outputs.tags }}
                  labels: ${{ steps.meta-web.outputs.labels }}

            - name: Extract metadata for monitor app
              id: meta-monitor
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/monitor

            - name: Build and push Docker image for monitor app
              id: push-monitor
              uses: docker/build-push-action@v6
              with:
                  context: ./apps/monitor
                  push: true
                  tags: ${{ steps.meta-monitor.outputs.tags }}
                  labels: ${{ steps.meta-monitor.outputs.labels }}
