name: Publish

on:
    push:
        tags:
            - "*"
    workflow_dispatch:

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        strategy:
            matrix:
                platform:
                    - linux/amd64
                    - linux/arm64

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata for @miru/web
              id: meta-web
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/web
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                  flavor: |
                      latest=true

            - name: Build and push Docker image for @miru/web
              id: push-web
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/web/Dockerfile
                  push: true
                  tags: ${{ steps.meta-web.outputs.tags }}
                  labels: ${{ steps.meta-web.outputs.labels }}
                  platforms: ${{ matrix.platform }}

            - name: Extract metadata for @miru/monitor
              id: meta-monitor
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/monitor
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                  flavor: |
                      latest=true

            - name: Build and push Docker image for @miru/monitor
              id: push-monitor
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/monitor/Dockerfile
                  push: true
                  tags: ${{ steps.meta-monitor.outputs.tags }}
                  labels: ${{ steps.meta-monitor.outputs.labels }}
                  platforms: ${{ matrix.platform }}
