name: Deploy Canary

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build and Publish
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        strategy:
            fail-fast: false
            matrix:
                platform:
                    - linux/amd64
                    - linux/arm64
        steps:
            - name: Prepare
              run: |
                  platform=${{ matrix.platform }}
                  echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract metadata for @miru/web
              id: meta-web
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}/web
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                      type=raw,value=canary
                  flavor: |
                      latest=false

            - name: Build @miru/web by digest
              id: build-web
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/web/Dockerfile
                  platforms: ${{ matrix.platform }}
                  labels: ${{ steps.meta-web.outputs.labels }}
                  tags: ghcr.io/${{ github.repository }}/web
                  outputs: type=image,push-by-digest=true,name-canonical=true,push=true

            - name: Export web digest
              run: |
                  mkdir -p ${{ runner.temp }}/digests-web
                  digest="${{ steps.build-web.outputs.digest }}"
                  touch "${{ runner.temp }}/digests-web/${digest#sha256:}"

            - name: Upload web digest
              uses: actions/upload-artifact@v4
              with:
                  name: digests-web-${{ env.PLATFORM_PAIR }}
                  path: ${{ runner.temp }}/digests-web/*
                  if-no-files-found: error
                  retention-days: 1

            - name: Extract metadata for @miru/monitor
              id: meta-monitor
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository }}/monitor
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                      type=raw,value=canary
                  flavor: |
                      latest=false

            - name: Build @miru/monitor by digest
              id: build-monitor
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./apps/monitor/Dockerfile
                  platforms: ${{ matrix.platform }}
                  labels: ${{ steps.meta-monitor.outputs.labels }}
                  tags: ghcr.io/${{ github.repository }}/monitor
                  outputs: type=image,push-by-digest=true,name-canonical=true,push=true

            - name: Export monitor digest
              run: |
                  mkdir -p ${{ runner.temp }}/digests-monitor
                  digest="${{ steps.build-monitor.outputs.digest }}"
                  touch "${{ runner.temp }}/digests-monitor/${digest#sha256:}"

            - name: Upload digest
              uses: actions/upload-artifact@v4
              with:
                  name: digests-monitor-${{ env.PLATFORM_PAIR }}
                  path: ${{ runner.temp }}/digests-monitor/*
                  if-no-files-found: error
                  retention-days: 1

    merge:
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Download @miru/web digest
              uses: actions/download-artifact@v4
              with:
                  path: ${{ runner.temp }}/digests-web
                  pattern: digests-web-*
                  merge-multiple: true

            - name: Extract metadata for @miru/web
              id: meta-web
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/web
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                      type=raw,value=canary
                  flavor: |
                      latest=false

            - name: Create @miru/web manifest list and push
              working-directory: ${{ runner.temp }}/digests-web
              run: |
                  docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
                    $(printf 'ghcr.io/${{ github.repository }}/web@sha256:%s ' *)

            - name: Inspect image
              run: |
                  docker buildx imagetools inspect ghcr.io/${{ github.repository }}/web:${{ steps.meta-web.outputs.version }}

            - name: Download @miru/monitor digest
              uses: actions/download-artifact@v4
              with:
                  path: ${{ runner.temp }}/digests-monitor
                  pattern: digests-monitor-*
                  merge-multiple: true

            - name: Extract metadata for @miru/monitor
              id: meta-monitor
              uses: docker/metadata-action@v5
              with:
                  images: |
                      ghcr.io/${{ github.repository }}/monitor
                  tags: |
                      type=semver,pattern={{version}}
                      type=sha
                      type=raw,value=canary
                  flavor: |
                      latest=false

            - name: Create @miru/monitor manifest list and push
              working-directory: ${{ runner.temp }}/digests-monitor
              run: |
                  docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
                    $(printf 'ghcr.io/${{ github.repository }}/monitor@sha256:%s ' *)

            - name: Inspect image
              run: |
                  docker buildx imagetools inspect ghcr.io/${{ github.repository }}/monitor:${{ steps.meta-monitor.outputs.version }}
